# Generated by Django 5.0.1 on 2024-01-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reading_ticket',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер читательского билета'),
        ),
    ]
